### ISSUE TITLE
Run Episim Berlin scenario with facility file

### ISSUE THREAD

**Issue by Qinnnnn** [matsim-org/matsim-episim-libs#90]
Hello, first thanks for your great work.

I am recently running Episim for Munich with facility files. I would like to run the Berlin scenario with facilities as well for comparison. 
I found some input files from: https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/episim/openDataModel/input/
-plan file: be_2020-week_snz_entirePopulation_emptyPlans_withDistricts_25pt_split.xml.gz
-event file: be_2020-week_snz_episim_events_wt_25pt_split.xml.gz
-facility file: be_2020-facilities_assigned_simplified_grid.xml.gz

Could you help to confirm if they are the right input files for running the Berlin scenario with facilities? If not, what would be the proper files?

Thanks!

**Comment by rakow** [comment]
This Berlin model runs without a separate facility file. The facilities are derived implicitly by using the link ids of the activities. The file you mentioned is not needed to run the model, probably it won't even work when you use it, because it is aggregated.

All you need is the population and the event file.

**Comment by Qinnnnn** [comment]
Thank you for your answer. Before closing the issue, could you help me to confirm the components of these two event files:
1. be_2020-week_snz_episim_events_wt_25pt_split.xml.gz (https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/episim/openDataModel/input/)
2. berlin-v5.4-1pct.output_events_for_episim.xml.gz (https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/")

Do they include activities of the agents across all modes (car, pt, walk, cycling)? or do they only include activities for certain purposes by certain modes?

**Comment by rakow** [comment]
These are two different models, but they contain all activities for all modes. However, the activity types are different and (1) does not contain facility ids.

**Comment by rakow** [comment]
Sorry, I mixed it up a bit. (2) does not contain facility Ids, and is using link ids instead. In any case, a separate facility file is not necessary.
