### ISSUE TITLE
Some useless code?

### ISSUE THREAD

**Issue by elect86** [matsim-org/matsim-episim-libs#93]
I guess there is some legacy code [here](https://github.com/matsim-org/matsim-episim-libs/blob/master/src/main/java/org/matsim/run/modules/SnzCologneProductionScenario.java#L250)

where `progressionConfig` is being set twice, second time being [here](https://github.com/matsim-org/matsim-episim-libs/blob/master/src/main/java/org/matsim/run/modules/SnzCologneProductionScenario.java#L254)

Is the last one the correct one?

**Comment by rakow** [comment]
Yes, the last one will overwrite any previous config.
