### ISSUE TITLE
No interaction cross over different activity type?

### ISSUE THREAD

**Issue by Qinnnnn** [matsim-org/matsim-episim-libs#95]
Hello, 

I am running the OpenBerlinScenario. The results show that the infections were only happened between "home_home", "work_work", "shopping_shopping", "leisure_leisure"...They only happened within the same activity type. 

I think this is because the way of creating facility id (activityType_linkId), which makes the facilities are specified to type+link.

but in reality, it will have cross interaction, for example, shopping (shopper) interacts with work (service people), work (teacher) interacts with education (student)... Can this be implemented in Episim?

Thanks in advance

**Comment by rakow** [comment]
Yes, it all depends on where the activity is taking place. Maybe rather have a look at this model: https://depositonce.tu-berlin.de/handle/11303/12695.2

Cross over interaction works out-of-the box if activities are performed at the same facility. This might not be the case in the OpenBerlinScenario.
